.github/workflows/main.yml
.gitignore
poetry.lock
src/sqlfmt/cli.py
tests/functional_tests/test_end_to_end.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_report.py
tox.ini

fixes a few small issues with sqlfmt on windows

Feature/sc 82/debug sqlfmt on windows

---

.gitignore
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt/splitter.py
tests/data/unformatted/101_multiline.sql
tests/data/unformatted/102_lots_of_comments.sql
tests/data/unit_tests/test_splitter/test_simple_comment_split.sql
tests/functional_tests/test_end_to_end.py
tests/functional_tests/test_general_formatting.py

- add new test data file
- fix merging across comments

bug/sc 91/do not merge across a comment

---

src/sqlfmt/dialect.py
src/sqlfmt/formatter.py
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt/splitter.py
tests/data/preformatted/002_select_from_where.sql
tests/data/preformatted/004_with_select.sql
tests/data/unformatted/100_select_case.sql
tests/data/unformatted/101_multiline.sql
tests/data/unformatted/103_window_functions.sql
tests/data/unformatted/200_base_model.sql
tests/data/unit_tests/test_merger/test_split_into_segments.sql
tests/functional_tests/test_end_to_end.py
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_line.py
tests/unit_tests/test_merger.py
tests/unit_tests/test_splitter.py
tests/util.py

- add failing test
- creates v1 implememtation. need to refactor merging entirely.
- refactors merger
- finish refactor of merger
This ended up being much more than a simple bug fix. This PR completely refactors the merger to greatly simplify the logic. The new merger creates output that was superior than some of the existing test results, so those have been updated

feature/sc 45/improve wrapping of window functions

---

CHANGELOG.md
src/sqlfmt/cli.py
src/sqlfmt/mode.py
src/sqlfmt/report.py
tests/functional_tests/test_end_to_end.py

- add failing test
- add quiet option, mute report
- update changelog

feature/sc 106/create a quiet mode

---

CHANGELOG.md
src/sqlfmt/dialect.py
src/sqlfmt/splitter.py
tests/data/unformatted/100_select_case.sql
tests/data/unit_tests/test_splitter/test_comment_split_impact_on_open_brackets.sql
tests/unit_tests/test_splitter.py

- fix: fix bug with closing brackets caused by comment splits
- fix: update regex to allow for comments without leading spaces

bug/sc 118/closing brackets are not being copied correctly

---

.github/workflows/test.yml
CHANGELOG.md
README.md
mypy.ini
poetry.lock
pyproject.toml
src/sqlfmt/api.py
src/sqlfmt/cli.py
src/sqlfmt_primer/primer.py
tests/unit_tests/test_api.py

- refactor api.run to return report object
- feat: add a basic primer cli
- fix: use quiet option
- feat: adds caching to primer

feature/sc 98/use gitlab s dbt project as sqlfmt primer

---

CHANGELOG.md
src/sqlfmt/api.py
src/sqlfmt/cli.py
src/sqlfmt/report.py
tests/functional_tests/test_end_to_end.py
tests/unit_tests/test_api.py
tests/unit_tests/test_cli.py

- feat: accept sql on stdin
- refactor: clean up path weirdness
- refactor: reorder fns in api

feature/sc 101/support stdin

---

CHANGELOG.md
src/sqlfmt/api.py
src/sqlfmt/cache.py
src/sqlfmt/line.py
src/sqlfmt/report.py
src/sqlfmt_primer/primer.py
tests/conftest.py
tests/functional_tests/test_end_to_end.py
tests/unit_tests/test_api.py
tests/unit_tests/test_cache.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_line.py
tests/unit_tests/test_merger.py
tests/unit_tests/test_parser.py
tests/unit_tests/test_splitter.py
tests/util.py

- feature: add cache
- chore: improve cache test coverage
- chore: increase test cov across modules

feature/sc 100/implement simple caching so we don t format

---

CHANGELOG.md
src/sqlfmt/dialect.py
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt/splitter.py
tests/data/unformatted/104_joins.sql
tests/data/unit_tests/test_merger/test_merge_lines_split_by_operators.sql
tests/data/unit_tests/test_splitter/test_simple_comment_split.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_line.py
tests/unit_tests/test_merger.py
tests/unit_tests/test_splitter.py

- feature: merge operator-split rows
- feature: split all rows on operators, improve merging of operators
- feature: merge lines following operator singletons

feature/sc 138/partially merge rows if split by operators

---

CHANGELOG.md
sqlfmt
src/sqlfmt/line.py
src/sqlfmt/merger.py
tests/data/unit_tests/test_merger/test_merge_chained_parens.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_merger.py

- fix: improve merging of chained brackets

feature/sc 139/fix merging sub statements

---

.pre-commit-hooks.yaml
README.md
poetry.lock
pyproject.toml

- feature: add pre-commit hook config
- fix: move platformdirs to required dependency

feature/sc 160/pre commit hook

---

.gitignore
CHANGELOG.md
Makefile
poetry.lock
pyproject.toml
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt_primer/__main__.py

- feature: add profiling for sqlfmt_primer, with simple make profiling command
- fix: fix makefile prereq, add snakeviz dependency
- refactor: improve merger performance
- refactor: add some caching to line properties

feature/sc 44/add profiling improve performance

---

README.md

I found I had to add a "v" to the beginning of the `rev` tag for in my `pre-commit-config.yaml`.

Update README pre-commit guidance

---

CHANGELOG.md
src/sqlfmt/api.py

fix: import asyncio directly, not from black

---

.github/workflows/test.yml
CHANGELOG.md
README.md
poetry.lock
pyproject.toml
src/sqlfmt/cli.py
src/sqlfmt/exception.py
src/sqlfmt/formatter.py
src/sqlfmt/jinjafmt.py
src/sqlfmt/line.py
src/sqlfmt/mode.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/101_multiline.sql
tests/data/unformatted/108_test_block.sql
tests/data/unformatted/200_base_model.sql
tests/data/unformatted/300_jinjafmt.sql
tests/functional_tests/test_end_to_end.py
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_jinjafmt.py
tox.ini

- feature: format contents of jinja tags
- chore: improve jinjafmt test coverage

feature/sc 50/use black to format within common jinja tags

---

src/sqlfmt/line.py
src/sqlfmt/splitter.py

- refactor: simplify splitter.py #96
- refactor: fewer returns in render method

chore/issue 96/refactor splitter

---

.github/workflows/test.yml
tox.ini

Chore: add coverage job to CI

---

CHANGELOG.md
src/sqlfmt/dialect.py
tests/data/unformatted/201_basic_snapshot.sql
tests/functional_tests/test_end_to_end.py
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_dialect.py

- fix: add support for snapshot blocks

fix/issue 137/snapshot blocks

---

CHANGELOG.md
README.md
src/sqlfmt/api.py
src/sqlfmt/cli.py
src/sqlfmt/config.py
src/sqlfmt/mode.py
src/sqlfmt_primer/primer.py
tests/data/config/exclude_config.toml
tests/unit_tests/test_api.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_config.py

feat: add cli option for excluding paths

---

CHANGELOG.md
README.md
src/sqlfmt/jinjafmt.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/300_jinjafmt.sql
tests/unit_tests/test_jinjafmt.py

- feat: jinjafmt python reserved words
- chore: update primer
- refactor: do not hardcode list of python keywords
closes #177 
closes #155

Feature: Enable black on jinja containing python reserved words

---

CHANGELOG.md
src/sqlfmt/api.py
src/sqlfmt/cache.py
src/sqlfmt/cli.py
src/sqlfmt/mode.py
tests/conftest.py
tests/functional_tests/test_end_to_end.py
tests/unit_tests/test_api.py
tests/unit_tests/test_cache.py
tests/util.py

- feat: add reset cache option
closes #184

Feature: Add reset cache CLI option

---

CHANGELOG.md
README.md
src/sqlfmt/actions.py
src/sqlfmt/analyzer.py
src/sqlfmt/cli.py
src/sqlfmt/config.py
src/sqlfmt/dialect.py
src/sqlfmt/formatter.py
src/sqlfmt/jinjafmt.py
src/sqlfmt/line.py
src/sqlfmt/mode.py
src/sqlfmt/node.py
src/sqlfmt/node_manager.py
src/sqlfmt/splitter.py
tests/conftest.py
tests/data/config/dialect_config.toml
tests/data/config/dialect_name_config.toml
tests/data/config/invalid_key_config.toml
tests/functional_tests/test_end_to_end.py
tests/unit_tests/test_actions.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_config.py
tests/unit_tests/test_dialect.py
tests/unit_tests/test_jinjafmt.py
tests/unit_tests/test_line.py
tests/unit_tests/test_mode.py
tests/unit_tests/test_node.py
tests/unit_tests/test_node_manager.py
tests/unit_tests/test_splitter.py

- feat: add dialect CLI option, add config file validation
- refactor: create NodeManager and remove Node.from_token
- feat #193: stop lowercasing names when clickhouse dialect is used

feat/issue 193/support clickhouse

---

CHANGELOG.md
src/sqlfmt/dialect.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/104_joins.sql
tests/data/unformatted/115_select_star_except.sql
tests/data/unformatted/212_http_2019_cms_14_02.sql
tests/data/unit_tests/test_merger/test_merge_chained_parens.sql
tests/unit_tests/test_node_manager.py

- fix #218: add a space between using and bracket
- chore: update primer and changelog

fix/issue 218/support using

---

CHANGELOG.md
src/sqlfmt/jinjafmt.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/213_gitlab_fct_sales_funnel_target.sql
tests/data/unformatted/300_jinjafmt.sql

fix #236: do not subtract prefix from running length in jinjafmt

---

CHANGELOG.md
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt/node.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/120_array_literals.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_line.py
tests/unit_tests/test_node.py

- fix #235: not all square brackets are array index operators
- chore: bump primer ref; add uncommitted test file

fix/issue 235/array literals are not index operators

---

src/sqlfmt/merger.py
src/sqlfmt/segment.py
tests/unit_tests/test_merger.py
tests/unit_tests/test_segment.py

refactor: create segment class to wrap a list of lines

---

CHANGELOG.md
README.md
poetry.lock
pyproject.toml
src/sqlfmt/__main__.py
src/sqlfmt/api.py
src/sqlfmt/cli.py
src/sqlfmt/mode.py
src/sqlfmt_primer/primer.py
tests/conftest.py
tests/unit_tests/test_api.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_mode.py

- refactor: pull get_matching_paths out of api.run
- feat #231: add progress bar
- fix: make mode.dialect access faster
- feat: add __main__ for module calling
- fix: stop copying the cache in multiprocessing mode
- feat: add VS Code section to readme, fix headings in changelog

feat/issue 231/add progress bar

---

CHANGELOG.md
src/sqlfmt/cli.py
tests/unit_tests/test_cli.py

- feat: config with env vars, close #251

Feature: Configure any option using env vars

---

.github/workflows/codeql-analysis.yml
.github/workflows/primer.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/static.yml
.github/workflows/test-coverage.yml
.github/workflows/test.yml

chore: refactor github set output; bump action versions

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
tests/unit_tests/test_rule.py

* feat: add is (not) distinct from support #327

Add is (not) distinct from Support

---

CHANGELOG.md
src/sqlfmt/api.py
src/sqlfmt/cli.py
src/sqlfmt/exception.py
src/sqlfmt/mode.py
src/sqlfmt/token.py
tests/unit_tests/test_api.py
tests/unit_tests/test_cli.py

Lex output for safety check

---

CHANGELOG.md
src/sqlfmt/formatter.py
src/sqlfmt_primer/primer.py
tests/data/unformatted/126_blank_lines.sql
tests/data/unformatted/202_unpivot_macro.sql
tests/data/unformatted/203_gitlab_email_domain_type.sql
tests/data/unformatted/205_rittman_hubspot_deals.sql
tests/data/unformatted/207_rittman_int_journals.sql
tests/data/unformatted/208_rittman_int_plan_breakout_metrics.sql
tests/data/unformatted/209_rittman_int_web_events_sessionized.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_formatter.py

- feat: remove extra blank lines, close #249
- chore: bump primer refs

Remove Excess Blank Lines

---

.github/workflows/publish.yml

Setup docker buildx and qemu to support platforms

---

CHANGELOG.md
src/sqlfmt/node_manager.py
tests/data/unformatted/900_create_view.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_analyzer.py

fix: make bracket comparison case insensitive

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
src/sqlfmt_primer/primer.py
tests/data/fast/unformatted/103_window_functions.sql
tests/data/unformatted/103_window_functions.sql
tests/unit_tests/test_rule.py

Support all valid frame clauses

---

CHANGELOG.md
src/sqlfmt/actions.py
src/sqlfmt/api.py
src/sqlfmt/comment.py
src/sqlfmt/line.py
src/sqlfmt/merger.py
src/sqlfmt/splitter.py
tests/data/unformatted/101_multiline.sql
tests/data/unformatted/218_multiple_c_comments.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_analyzer.py
tests/unit_tests/test_api.py
tests/unit_tests/test_comment.py
tests/unit_tests/test_line.py

fix #419: handle multiple c-style comments

---

CHANGELOG.md
src/sqlfmt/rules/core.py
tests/unit_tests/test_rule.py

feat: support <=> operator

---

CHANGELOG.md
src/sqlfmt/api.py
src/sqlfmt/comment.py
src/sqlfmt/rules/common.py
tests/data/unformatted/128_double_slash_comments.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_comment.py
tests/unit_tests/test_rule.py

fix #468: support snowflake // comments

---

CHANGELOG.md
src/sqlfmt/node_manager.py
tests/data/unformatted/133_for_else.sql
tests/functional_tests/test_general_formatting.py

fix: support else in for loops

---

CHANGELOG.md
src/sqlfmt/operator_precedence.py
src/sqlfmt/rules/core.py
tests/unit_tests/test_rule.py

fix: support pg LIKE operators, ~~ etc

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
tests/unit_tests/test_rule.py

fix: add support for union by name

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
tests/unit_tests/test_rule.py

fix: parse interval as word operator

---

src/sqlfmt/rules/__init__.py
tests/unit_tests/test_rule.py

fix: allow filter() and isnull() with no space

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
tests/data/unformatted/135_star_columns.sql
tests/functional_tests/test_general_formatting.py
tests/unit_tests/test_rule.py

fix: lex *columns as a name before lexing *

---

.github/workflows/test.yml
CHANGELOG.md

closes https://github.com/tconbeer/sqlfmt/issues/648

chore: add py 313 to test matrix

---

CHANGELOG.md
src/sqlfmt/tokens.py
tests/data/unformatted/132_spark_number_literals.sql
tests/unit_tests/test_node_manager.py

fix: lowercase numbers

---

CHANGELOG.md
src/sqlfmt/rules/unsupported.py
tests/data/unformatted/999_unsupported_ddl.sql

fix: lex quoted names as data in unsupported ddl blocks

---

CHANGELOG.md
src/sqlfmt/rules/__init__.py
src/sqlfmt/rules/common.py
src/sqlfmt/rules/pragma.py
tests/data/unformatted/412_pragma.sql
tests/functional_tests/test_general_formatting.py

feat: add support for pragma, set, call
