.gitignore, src/sqlfmt/dialect.py, src/sqlfmt/line.py, src/sqlfmt/splitter.py, src/sqlfmt/token.py, tests/conftest.py, tests/data/unformatted/104_joins.sql, tests/functional_tests/test_end_to_end.py, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_dialect.py, tests/unit_tests/test_line.py, tests/util.py
- add failing test for join formatting
- add join to unterminated keywords
- add on and using as operators
- automatically delete test results before test run
- create new token type
- fix join regex
This doesn't get us all the way there; formatting test is still failing. I'm punting on the hard stuff until we get splits for operators sorted in 0.2(+). But with reasonable well-formed input, this looks nice, and it's consistent with the rest of the scheme.
=> feature/sc 52/split joins on on using

CHANGELOG.md, src/sqlfmt/dialect.py, src/sqlfmt/line.py, tests/unit_tests/test_dialect.py, tests/unit_tests/test_line.py
- fix: use lazy regex for jinja tags
- fix: do not insert space before jinja tag if it is a relation name
- fix: lowercase word operators
- update changelog
=> bug/sc 109/false positive syntax errors in gitlab dbt

src/sqlfmt/line.py, tests/unit_tests/test_line.py
After some effort, I abandoned my attempt to refactor Line.from_nodes -- turns out we're actually pretty efficient, and there is too much state to track (in Nodes and Lines) to do it as simply/efficiently another way.
=> refactor: remove unused line props

CHANGELOG.md, src/sqlfmt/actions.py, src/sqlfmt/dialect.py, src/sqlfmt/exception.py, src/sqlfmt/line.py, src/sqlfmt_primer/primer.py, tests/unit_tests/test_actions.py, tests/unit_tests/test_analyzer.py, tests/unit_tests/test_api.py, tests/unit_tests/test_line.py
- chore: add unit tests for actions module
- fix: safely handle 'end', do not assume it is a kw
=> fix/sc 178/safe parse end as kw or name

CHANGELOG.md, README.md, src/sqlfmt/formatter.py, src/sqlfmt/line.py, src/sqlfmt/node.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/107_jinja_blocks.sql, tests/data/unformatted/113_utils_group_by.sql, tests/data/unformatted/202_unpivot_macro.sql, tests/functional_tests/test_end_to_end.py, tests/functional_tests/test_general_formatting.py
-   sqlfmt is now more conservative about preserving whitespace around jinja expressions when we remove newlines (closes #162, #165)
-   Jinja blocks are now dedented before line merging, instead of after. This results in small changes to formatted output in some cases where jinja blocks are used
-   Fixes an issue where jinja else and elif statements could cause unstable formatting. May impact whitespace for the tokens following `{% else %}` and `{% elif %}` statements
=> Fix: Improve Jinja Whitespace Control

CHANGELOG.md, src/sqlfmt/jinjafmt.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/300_jinjafmt.sql, tests/unit_tests/test_jinjafmt.py
=> Fix: do not indent multiline tags unless black actually ran

CHANGELOG.md, src/sqlfmt/jinjafmt.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/202_unpivot_macro.sql, tests/unit_tests/test_jinjafmt.py
=> fix: remove trailing commas added to macro definitions by black

pyproject.toml, src/sqlfmt/comment.py, src/sqlfmt/formatter.py, src/sqlfmt/jinjafmt.py, src/sqlfmt/line.py, src/sqlfmt/merger.py, src/sqlfmt/node.py, src/sqlfmt/splitter.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/213_gitlab_fct_sales_funnel_target.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_splitter.py
This PR solves the instability described in #175 by making two changes:
- fix: removing caching of node, line, comment props, which can cause issues when objects are mutated by jinjaformatter
- fix #175: add extra split before multiline jinja nodes
It also improves the style where singleton operators and multiline jinja nodes interact:
- fix: allow more merging of multiline jinja nodes
=> fix/issue 175/unstable jinja and operators

CHANGELOG.md, src/sqlfmt/actions.py, src/sqlfmt/dialect.py, src/sqlfmt_primer/primer.py, tests/data/preformatted/400_create_table.sql, tests/data/unformatted/400_create_fn_and_select.sql, tests/functional_tests/test_end_to_end.py, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_actions.py, tests/unit_tests/test_dialect.py
This closes #243
We parse all known DDL/DML keywords as DATA tokens if they appear at depth 0 (e.g., not as an alias inside of a select statement).
This creates one known issue where unsupported SQL interacts with jinja in complex ways, but I think it's better than just blindly charging ahead and formatting DDL we don't understand.
- feat: lex unsupported ddl as DATA token so we don't format it
- fix: fix depth calc in handle_unsupported_ddl
- fix: parse semicolons in quotes as part of unsupported ddl token
- fix: insert ddl should not match snowflake insert() fn
- fix: allow sql comments in ddl
- chore: update changelog, primer
=> Feature: Detect unsupported SQL commands and abort formatting

CHANGELOG.md, src/sqlfmt/comment.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/102_lots_of_comments.sql, tests/unit_tests/test_comment.py
- fix #319: no trailing whitespace on empty comments
- chore: update primer refs
=> Do not add trailing whitespace to empty comments

CHANGELOG.md, poetry.lock, pyproject.toml, src/sqlfmt/actions.py, src/sqlfmt/jinjafmt.py, src/sqlfmt/line.py, src/sqlfmt/merger.py, src/sqlfmt/node.py, src/sqlfmt/node_manager.py, src/sqlfmt/splitter.py, src/sqlfmt/token.py, tests/unit_tests/test_actions.py, tests/unit_tests/test_analyzer.py, tests/unit_tests/test_jinjafmt.py, tests/unit_tests/test_line.py, tests/unit_tests/test_node.py, tests/unit_tests/test_node_manager.py
- refactor: replace enum list comparisons with cached property. 11% reduction in gitlab runtime
- refactor: more token type caching, further 8% reduction in runtime
- refactor: clean up line.__str__
=> Perf: Refactor Enum comparisons

CHANGELOG.md, src/sqlfmt/actions.py, src/sqlfmt/analyzer.py, src/sqlfmt/exception.py, src/sqlfmt/node_manager.py, src/sqlfmt/rules/__init__.py, src/sqlfmt/rules/core.py, src/sqlfmt/rules/jinja.py, src/sqlfmt/splitter.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/204_gitlab_tag_validation.sql, tests/data/unformatted/214_get_unique_attributes.sql, tests/data/unformatted/215_gitlab_get_backup_table_command.sql, tests/data/unformatted/217_dbt_unit_testing_csv.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_actions.py, tests/unit_tests/test_splitter.py
This closes #338 , and also handles some long-overdue refactoring of how we lex jinja blocks. Namely, now that we support multiple rulesets, we can do more of the lexing in the main loop, rather than in a specialized jinja-block-specific loop. This actually simplifies quite a bit of the lexing logic.
- wip: refactor jinja lexing
- refactor: use a single StopLexing exception'
- refactor: handle jinja block keywords with new action
- refactor: remove unused analyzer.stops
- fix: allow empty jinja blocks
- fix: fix issue with whitespace and data tokens
- chore: bump primer ref
=> Support Nested Set and Call Blocks

CHANGELOG.md, src/sqlfmt/api.py, src/sqlfmt/mode.py, src/sqlfmt_primer/primer.py, tests/unit_tests/test_api.py
Closes #354 
This allows to use the CLI against files which are named `.{something}.sql` and `.{something}.sql.jinja`.
I'll be the first to admit that I know nothing about python as a language, so there might be a better way of doing this. But it passes the tests and explains my issues goal.
=> Match end of suffix against .sql and .sql.jinja

.github/workflows/publish.yml
This will help to speed up the container on ARM machines like the the newer Apple products.
=> Add multiple platforms to docker build

CHANGELOG.md, src/sqlfmt/comment.py, src/sqlfmt/exception.py, src/sqlfmt/jinjafmt.py, src/sqlfmt/line.py, src/sqlfmt/merger.py, src/sqlfmt/splitter.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/101_multiline.sql, tests/data/unformatted/102_lots_of_comments.sql, tests/data/unformatted/113_utils_group_by.sql, tests/data/unformatted/127_more_comments.sql, tests/data/unformatted/200_base_model.sql, tests/data/unformatted/209_rittman_int_web_events_sessionized.sql, tests/data/unit_tests/test_merger/test_merge_inline_comments.sql, tests/data/unit_tests/test_merger/test_no_merge_formatting_disabled.sql, tests/data/unit_tests/test_merger/test_no_merge_short_multiline_nodes.sql, tests/data/unit_tests/test_splitter/test_simple_comment_split.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_comment.py, tests/unit_tests/test_line.py, tests/unit_tests/test_merger.py, tests/unit_tests/test_splitter.py
This PR ended up totally rethinking and rewriting comment handling. It was spurred by #348, but ended up doing more.
For the purposes of stability, we no longer push long inline comments to be standalone comments. This also helps
preserve the meaning of the position of the inline comments (this isn't always important, but sometimes it is).
This means that sometimes lines can exceed the max desired line length (including the inline comment).
- feat: revisit comments, close #348
- chore: improve unit testing and docs
- fix: allow merging if lines end in trailing inline comment
- fix: allow merging ahead of inline comments'
- fix: allow merging of blank lines after inline comments
- fix: keep inline comments inline
- fix: strip whitespace when splitting comments onto multiple lines
- fix: …
=> Comments, revisited

CHANGELOG.md, src/sqlfmt/jinjafmt.py, src/sqlfmt/line.py, src/sqlfmt_primer/primer.py, tests/data/unformatted/107_jinja_blocks.sql, tests/data/unformatted/108_test_block.sql, tests/data/unformatted/126_blank_lines.sql, tests/data/unformatted/201_basic_snapshot.sql, tests/data/unformatted/202_unpivot_macro.sql, tests/data/unformatted/203_gitlab_email_domain_type.sql, tests/data/unformatted/204_gitlab_tag_validation.sql, tests/data/unformatted/205_rittman_hubspot_deals.sql, tests/data/unformatted/207_rittman_int_journals.sql, tests/data/unformatted/208_rittman_int_plan_breakout_metrics.sql, tests/data/unformatted/209_rittman_int_web_events_sessionized.sql, tests/data/unformatted/214_get_unique_attributes.sql, tests/data/unformatted/215_gitlab_get_backup_table_command.sql, tests/data/unformatted/217_dbt_unit_testing_csv.sql, tests/unit_tests/test_formatter.py, tests/unit_tests/test_jinjafmt.py
closes #403 
This represents a major update to the sqlfmt style. From the CHANGELOG:
-   the contents of jinja blocks are now indented if the block wraps onto multiple rows ([#403](https://github.com/tconbeer/sqlfmt/issues/403)). This is now the proper sqlfmt style:
```sql
select
some_field,
{% for some_item in some_sequence %}
some_function({{ some_item }}){% if not loop.last %}, {% endif %}
{% endfor %}
```
While in this simple example the new style makes it less clear that `some_field` and `some_function` are at the same SQL depth, the formatting of complex files with nested jinja blocks is much improved. For example:
```sql
{%- for col in cols -%}
{%- if col.column.lower() not in remove | map(
"lower"
) and col.column.lower() not in exclude | map("lower") -%}
{% do …
```
=> Indent jinja block contents

CHANGELOG.md, src/sqlfmt/config.py, tests/unit_tests/test_config.py
We need to call `absolute()` to convert a relative path to an absolute path before trying to compare parents, as `parents` is (per the docs), 'a purely lexical operation'.
Fixes https://github.com/tconbeer/sqlfmt/issues/426.
=> fix(config): handle mixed relative and absolute paths

CHANGELOG.md, src/sqlfmt/api.py, src/sqlfmt/cli.py, src/sqlfmt/config.py, src/sqlfmt/mode.py, src/sqlfmt/report.py, tests/unit_tests/test_api.py, tests/unit_tests/test_config.py
This reverts some of the changes in #427 , relying instead on click's path resolution.
To make apples-to-apples comparisons, we also have to resolve the exclude globs, and do that relative to the config file, if they are defined there. This defines previously undefined behavior about the exclude option in config files.
=> fix #431: evaluate exclude paths as absolute

CHANGELOG.md, src/sqlfmt/api.py, tests/data/unit_tests/test_api/test_file_discovery/a_directory/symlink_target_directory, tests/unit_tests/test_api.py
This PR updates the globbing behavior for the `--exclude` option in `api.get_matching_paths()` to rely only on `glob.glob()` instead of `Path.glob()`, the latter of which contains a bug on Python <3.13 such that it [does not always follow symlinked directories correctly](https://github.com/tconbeer/sqlfmt/issues/457).
=> fix #457: Make `--exclude` option follow symlinked directories

README.md
Follows up on #463 by updating the note about `sqlfmt` being in alpha status with a more verbose statement to encourage further `sqlfmt` adoption. I'll open a similar PR to update the docs.
=> Updating note about alpha status

CHANGELOG.md, src/sqlfmt/rules/core.py, tests/data/unformatted/131_assignment_statement.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_rule.py
=> fix #502: change lexing priority of walrus operator

CHANGELOG.md, src/sqlfmt/rules/__init__.py, tests/data/fast/unformatted/104_joins.sql, tests/data/unformatted/104_joins.sql, tests/unit_tests/test_rule.py
Hey 👋  A small addition to the current formatter (thanks for the work done there 👌 ). 
Main idea is to handle better left anti joins that are defined within [databricks](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-join.html)
before
```
select
...
from table_a left
anti join table_b using(key)
```
after
```
select
...
from table_a
left anti join table_b using(key)
```
Feel free to tell me if you want me to modify the content of this PR 🙏
=> feat(join-lint): handle left anti join

CHANGELOG.md, src/sqlfmt/actions.py, src/sqlfmt/rules/__init__.py, src/sqlfmt/rules/clone.py, src/sqlfmt/rules/function.py, src/sqlfmt/rules/grant.py, src/sqlfmt/rules/warehouse.py, src/sqlfmt_primer/primer.py, tests/data/preformatted/008_reserved_names.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_actions.py
=> fix: parse keywords as names if qualified by period

src/sqlfmt/comment.py, tests/data/unformatted/127_more_comments.sql
Prevent splitting of comments that contain Jinja tags as outlined in #628 
Add test to make sure does not split that comment.
=> Issue #628 do not split comments with jinja tags

CHANGELOG.md, src/sqlfmt/node_manager.py, src/sqlfmt/rules/__init__.py, src/sqlfmt/rules/core.py, src/sqlfmt/rules/unsupported.py, src/sqlfmt_primer/primer.py, tests/data/preformatted/401_create_row_access_policy.sql, tests/functional_tests/test_general_formatting.py, tests/unit_tests/test_actions.py, tests/unit_tests/test_node_manager.py
=> fix: refactor  unsupported DDL handling
